services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: config-server:latest
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ../repos:/repos
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - BASE_REPOS_PATH=${BASE_REPOS_PATH}
      - PATH_SWAGGER=${PATH_SWAGGER}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - THROTTLER_TTL=${THROTTLER_TTL}
      - THROTTLER_LIMIT=${THROTTLER_LIMIT}
    restart: unless-stopped
